### ISSUE TITLE
Launching http://cfregisters.org

### ISSUE THREAD

**Issue by jamiefolsom** [mit-history/cfrp#21]
This is to coordinate launch of the new http://cfregisters.org/ website, currently at http://staging.cfregisters.org/.

I would like to get this completed by Friday 6/9 if possible, Wed. 6/14 at the outside.

I welcome anyone's input.

TO DO
- [x] Pause work on the live database application (http://app.cfregisters.org) and put it into maintenance mode [@jamiefolsom / Sara]
- [x] Update staging database with latest code and BnF/Lagrange Data, in particular: #12, #17, #18, #19, #20 [@jamiefolsom]
- [x] Copy latest data from live application to the staging instance [@jamiefolsom]
- [x] Update http://staging.cfregisters.org/en/the-data/basic-tool to point to http://ui.cfregisters.org/ if it isn't already [@circa1977/@jamiefolsom]
- [x] Test integration of http://github.org/mit-history/rcf-ui with staging [@adimasci]

Launch [ @circa1977 / @jamiefolsom ]:
- [x] Change DNS entries as follows
  - [x] Production app (to "app-old" >> http://app-old.cfregisters.org/registers)
  - [x] Staging app (to "app" >> http://app.cfregisters.org/)
  - [x] Production RCF ui (to "ui-old" >> http://ui-old.cfregisters.org/)
  - [x] Staging RCF ui (to "ui" >> http://ui.cfregisters.org/)
  - [x] Production website (to "archive" >> http://archive.cfregisters.org/)
  - [x] Staging website (to "www/*" >> http://www.cfregisters.org/ *and* http://cfregisters.org/)

Jamie

**Comment by circa1977** [comment]
Howdy!

Here’s my list:

1. My usual caveat about not updating DNS or launching on a Friday leaving things to propagate when people might not be around :) I like Monday - Thur, 1st thing in the AM, to update DNS or launch a site. With that said, I’m on board with this timeframe.
2. Going live will entail me renaming the staging site directory to use the directory name that the live vhost currently points to (`www_html`). There should not be any DNS lag in this case, as live & staging are already on the same server, and renaming the directory will happen on the server.
3. I will update the Craft database config (`db.php`) to point to the correct database based on the incoming URL. (live vs. staging) when I rename the directories / go live.
4. @jamiefolsom, per [this template](https://github.com/hyperstudio/cfrp-craft/blob/updates/craft/templates/the-data/_basic.html) in the `updates` branch, that ui.cfregisters.org URL appears to be in place. A push to that branch deploys directly to staging.cfregisters.org, which will be the live site—what we see there is what we'll see at launch.
5. Whatever you want to call the previous instance (archive.cfregisters.org?) just point that CNAME at the same IP as the live + staging sites (162.247.143.150), and I’ll ask the hosting provider to point a corresponding vhost at that.

Thanks!

Mark

**Comment by jamiefolsom** [comment]
Hi, @circa1977. I agree we should steer clear of Friday. If we're ready Thursday, we'll do that, otherwise, first thing Monday will be the target. Thanks!

**Comment by adimascio** [comment]
Hi @jamiefolsom,

I've fetched a dump from cfrp-staging, rebuilt the materalized views, update the parse_lagrange.py script to match the "rcf_id" / "person_id" column changes re-run the parse_lagrange.py.

After that, the rcf-ui application seems to run OK

**Comment by jamiefolsom** [comment]
@adimascio Great! I am going to rebuild the staging database from a copy of the production database. If you would be so kind as to re-test again (against the live database) once that's complete, that would be great. I will let you know when that's complete. Thanks!

**Comment by jamiefolsom** [comment]
Hi, @adimascio,

I've repeated the data import and update process on a copy of the production database. 

That is now available at http://staging-app.cfregisters.org/. 

As a pre-launch test, it would be good to modify the configuration of [rcf-ui](http://ui.cfregisters.org), to attach the staging database to it, instead of its own separate db. 

If you would like to test this new db locally first, that's fine. If not, let me know and I will modify the configuration of rcf-ui. 

Then if you'd take a look, to be sure it's working properly, we'll be ready for the next step. Ideally, if we could get this done before the weekend, that would be great, so we can launch on Monday.

Thanks!

**Comment by circa1977** [comment]
Hi, @jamiefolsom!

Any timing updates on the launch?

Thanks!

**Comment by jamiefolsom** [comment]
Hi @circa1977, Yes, we've discovered a problem with an outside source of data which we have to pause and consider our options. Basically the UI which @adimascio and I have been working to integrate (http://ui.cfregisters.org/) depends on a website which is in flux. So either we'll launch without that UI (ie, tomorrow, I hope), or we're going to have to wait for the other site to come back online, and be reliable (ie, not tomorrow, and probably not this week). I will keep you posted. Thanks!

**Comment by adimascio** [comment]
I propose we temporarily drop the links to the La Grange website. It looks like no one is able to provide any reliable information on when (and even "if') it will be fixed.

**Comment by jamiefolsom** [comment]
@adimascio sounds good to me. If that's easy to do, would you deploy that change to [staging](https://rcf-ui-staging.herokuapp.com/)? Thanks!

**Comment by adimascio** [comment]
@jamiefolsom I've deployed the master branch on [rcf-ui-staging](https://rcf-ui-staging.herokuapp.com/) but got again the "Cannot GET /" error. How could I debug that ?

**Comment by jamiefolsom** [comment]
@adimascio I think that's because the PG connection being made by the application is not using sslmode. See: https://github.com/mit-history/rcf-ui/issues/2#issuecomment-307424445

I think that's required on Heroku, and it's done automatically when the database uses the DATABASE_URL config variable, but instead, we're building up the connection string piecemeal, using separate vars for each part of the connection, and leaving out `sslmode=require`.

See the docs [here](https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl) too. I think the place to do that is [here](https://github.com/mit-history/rcf-ui/blob/master/app/server/database.js#L6-L12). 

I've opened a PR, based on the [docs for pg-promise](https://github.com/vitaly-t/pg-promise/wiki/Connection-) that I think will do the trick. See: https://github.com/mit-history/rcf-ui/pull/3Syntax#configuration-object

Let me know if that looks good to you.

**Comment by jamiefolsom** [comment]
OK, @circa1977 -- I think we're almost ready to launch. Are you available to help today? I will update this issue with the remaining steps in detail. Let me know if/when you're ready to go.

**Comment by jamiefolsom** [comment]
@circa1977 I've detailed the steps for launch. I am just waiting on a green light from the team leads. If they don't reply today (it's 5pm in France), we should be able to move ahead with all but your part. Stand by!

**Comment by jamiefolsom** [comment]
@circa1977, I've added an A record to the cfregisters.org DNS zone file, which points archive.cfregisters.org to 162.247.143.150. The other apps have now been moved to the correct production URLs, so once we get the green light from Christian, Sara, or Agathe, we can flip the switch(es) on the Craft site, to move staging to production, and production to archive.

**Comment by circa1977** [comment]
Hey, @jamiefolsom!

My cutoff will be 2:30pm. If we get the 👍🏻 after that, I'll do this ~8:30am tomorrow (Wednesday).

Here's a refined/more accurate list on my part. Note there are **no** further DNS changes required.

* [ ] Back up Staging and Live DB on Arcustech server.
* [ ] Add line to Craft config in Updates branch to refer to “staging” database for live website URL requests
* [ ] Commit & push that update to `staging_html`
* [ ] Disable any deployment profiles that deploy Master to `www_html`
* [ ] Rename `www_html` dir to `archive_html`
* [ ] Rename `staging_html` to `www_html` – **The new site is live**
* [ ] Update Deploy profile for Updates branch to push to `www_html`
* [ ] Download a copy of `archive_html`, database backups
* [ ] Ask Arcustech to set up an archive.cfregisters.org vhost

Thanks!

**Comment by jamiefolsom** [comment]
Hi @circa1977, That sounds perfect. I don't imagine we'll hear back today, but I will let you know if I do before before 2:30pm. Thanks!

**Comment by jamiefolsom** [comment]
If we do start tomorrow AM, about what time Eastern do you expect the new site to be live? If you know, I will let the folks in France know, so that they can plan. Thanks!

**Comment by circa1977** [comment]
9:00 or 9:30am? Should be quick. I might prep some of it today.

**Comment by circa1977** [comment]
We're live!

**Comment by jamiefolsom** [comment]
Woot!

**Comment by adimascio** [comment]
Great Job ! It's nice to see this live…

…although I spotted a real issue on http://ui.cfregisters.org/plays : the authors are not correct in the table. Sorry for not having spotted this yesterday. I can see how to fix the issue, it's pretty easy. How should be proceed ? I can push a fix on the master branch of rcf-ui real quick

**Comment by jamiefolsom** [comment]
@adimascio sure!

**Comment by adimascio** [comment]
@jamiefolsom done, and published a new tag 1.2.2 on the rcf-ui repository

**Comment by circa1977** [comment]
[My launch checklist](https://github.com/mit-history/cfrp/issues/21#issuecomment-308179260) is complete.

**Comment by jamiefolsom** [comment]
Thanks for your hard work, @adimascio, @circa1977, @christopheryork et al!
